//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crowfunding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compaign
    {
        public Compaign()
        {
            this.Donations = new HashSet<Donation>();
            this.refunds = new HashSet<refund>();
            this.withdrawl_desciption = new HashSet<withdrawl_desciption>();
        }
    
        public int compaign_id { get; set; }
        public int compaign_creater_id { get; set; }
        public string compaign_description { get; set; }
        public string compaign_date_created { get; set; }
        public string compaign_title { get; set; }
    
        public virtual Profile Profile { get; set; }
        public virtual ICollection<Donation> Donations { get; set; }
        public virtual ICollection<refund> refunds { get; set; }
        public virtual ICollection<withdrawl_desciption> withdrawl_desciption { get; set; }
    }
}
