//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crowfunding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Donation
    {
        public int donation_reference { get; set; }
        public int donation_compaign_id { get; set; }
        public int donation_user_id { get; set; }
        public int donation_amount { get; set; }
        public string donation_date_created { get; set; }
    
        public virtual Compaign Compaign { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
