//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crowfunding.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CrowFudingEntities14 : DbContext
    {
        public CrowFudingEntities14()
            : base("name=CrowFudingEntities14")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Compaign> Compaigns { get; set; }
        public DbSet<Donation> Donations { get; set; }
        public DbSet<Profile> Profiles { get; set; }
        public DbSet<refund> refunds { get; set; }
        public DbSet<withdrawl_desciption> withdrawl_desciption { get; set; }
        public DbSet<withdrawls_request> withdrawls_request { get; set; }
    }
}
