//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crowfunding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        public Profile()
        {
            this.Compaigns = new HashSet<Compaign>();
            this.Donations = new HashSet<Donation>();
            this.refunds = new HashSet<refund>();
            this.withdrawl_desciption = new HashSet<withdrawl_desciption>();
        }
    
        public int user_id { get; set; }
        public string user_fname { get; set; }
        public string user_email { get; set; }
        public string user_address { get; set; }
        public string user_password { get; set; }
        public string user_Lastname { get; set; }
    
        public virtual ICollection<Compaign> Compaigns { get; set; }
        public virtual ICollection<Donation> Donations { get; set; }
        public virtual ICollection<refund> refunds { get; set; }
        public virtual ICollection<withdrawl_desciption> withdrawl_desciption { get; set; }
    }
}
