//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crowfunding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class refund
    {
        public int refund_id { get; set; }
        public int users_id { get; set; }
        public int Compaign_id { get; set; }
        public int Amount { get; set; }
        public Nullable<int> donation_reference { get; set; }
    
        public virtual Compaign Compaign { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
