//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crowfunding.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class withdrawl_desciption
    {
        public int withdrawl_reference { get; set; }
        public string withdrawl_discription { get; set; }
        public int withdrawl_user_id { get; set; }
        public int withdrawl_amount { get; set; }
        public int withdrawl_compaign_id { get; set; }
        public string donation_date_created { get; set; }
        public Nullable<int> withdrawl_status { get; set; }
    
        public virtual Compaign Compaign { get; set; }
        public virtual Profile Profile { get; set; }
        public virtual withdrawl_desciption withdrawl_desciption1 { get; set; }
        public virtual withdrawl_desciption withdrawl_desciption2 { get; set; }
    }
}
